Form/GalleryType.php
<?php

namespace Juice\UploadBundle\Form;

use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Liip\ImagineBundle\Imagine\Filter\FilterManager;
use Liip\ImagineBundle\Imagine\Filter\FilterConfiguration;
use Juice\UploadBundle\Form\Type\AbstractUploadType;

class GalleryType extends AbstractUploadType
{
    public function __construct(FilterManager $filterManager) {
        $this->filterConfiguration = $filterManager->getFilterConfiguration();
    }

    public function getParent()
    {
        return 'collection';
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        foreach($options['field_attr']  as $key => $value) {
            $view->vars['attr'][$key] = $value;
        }

        $this->addVars($view, $options);
        $this->addFilter($view);
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'field_attr' => array(),
            'default_data' => array(
                'data-form-kind' => 'image',
                'data-callback' => 'handleGalleryImage',
                'data-crop' => 'false',
            ),
            'options' => array(
                'label' => false,
                'attr' => array(
                    'class' => 'juice_upload_gallery_item',
                )
            ),
            'button_label' => 'Upload',
            'button_class' => '',
            'accept' => '',
            'multi' => true,
            'attr' => array(
                'class' => 'sortable'
            ),
            'allow_add' => true,
            'allow_delete' => true,
            'by_reference' => false
        ));
    }

    public function getName()
    {
        return 'juice_upload_gallery_field';
    }
}

Resources/views/bootstrap_form_fields.html.twig
{% block form_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            {% for error in errors %}
                <div class="label label-danger">{{ error.message }}</div>
            {% endfor %}
        {% endif %}
    {% endspaceless %}
{% endblock form_errors %}

{% block controls %}
    <div class="juice_upload_controls clearfix">
        <div class="juice_upload_button_container">
            <span class="btn btn-primary fileinput-button {{ form.vars.button_class }}">
                <i class="glyphicon glyphicon-plus"></i>
                <span>{{ form.vars.button_label }}</span>

                <!-- The file input field used as target for the file upload widget -->
                <input class="file_upload" type="file" name="file" accept="{{ form.vars.accept }}"  {% if form.vars.multi | default(false) %}multiple{% endif %}>
            </span>
        </div>

        <div class="juice_upload_progress_container">
            <div class="percent"></div>
            <span class="glyphicon glyphicon-refresh spin"></span>
        </div>
    </div>
{% endblock %}

{% block juice_upload_image_type_widget %}
    <div class="juice_upload clearfix" {% for key, value in form.vars.attr %}{{ key }}="{{ value }}" {% endfor %} data-input-name="{{ form.vars.full_name }}">
        {{ block('controls') }}
        {{ block('juice_upload_base_image') }}
    </div>
{% endblock %}

{% block juice_upload_file_type_widget %}
    <div class="juice_upload clearfix" {% for key, value in form.vars.attr %}{{ key }}="{{ value }}" {% endfor %} data-input-name="{{ form.vars.full_name }}">

        {{ block('controls') }}

        <div class="juice_upload_item file">
            <div class="file_container">
                {% if form.vars.value %}
                    <div class="alert alert-success juice_upload_file" role="alert">{{ form.vars.value }}<div class="button remove"><span class="glyphicon glyphicon-remove"></span></div></div>
                {%  endif %}
                <div class="hidden_form">{{ form_widget(form) }}</div>
            </div>
        </div>
    </div>
{% endblock %}

{% block juice_upload_gallery_field_widget %}
    <div class="juice_upload clearfix" {% for key, value in form.vars.attr %}{{ key }}="{{ value }}" {% endfor %} data-input-name="{{ form.vars.full_name }}" data-prototype="{{ form_widget(form.vars.prototype)|e }}">

        {{ block('controls') }}

        <div class="juice_upload_collection">
            {% for child in form.children %}
                {{ form_widget(child, {attr : { class : 'juice_upload_gallery_item' }}) }}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block juice_upload_gallery_item_type_widget %}
    {{ block('juice_upload_base_image') }}
{% endblock %}

{% block juice_upload_base_image %}
    <div class="juice_upload_item image">
        <div class="juice_upload_form_container">
            <div class="featured_layer"></div>
            <div class="edit_layer">
                <div class="buttons">
                    <div class="button remove"><span class="glyphicon glyphicon-remove"></span></div>
                </div>
            </div>
            <div class="file_container">
                {% if form.vars.value %}
                    {% set finalPath = final_upload_dir ~ "/" ~ form.vars.value %}
                    {% set tmpPath = tmp_upload_dir ~ "/" ~ form.vars.value %}

                    {% if finalPath | checkFile %}
                        <img src="{{ finalPath | imagine_filter(form.vars.attr.filter) }}" />
                    {%  elseif tmpPath | checkFile%}
                        <img src="{{ tmpPath | imagine_filter(form.vars.attr.filter) }}" />
                    {%  else %}
                        Image ERROR!!!
                    {%  endif %}
                {%  endif %}
                <div class="hidden_form">
                    {{ form_widget(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Resources/views/form_fields.html.twig
{% block form_row %}
    {% spaceless %}
        {% if attr.class is defined %}
            {% set attr = attr | merge({'class' : attr.class ~ ' form-control'}) %}
        {% else %}
            {% set attr = attr | merge({'class' : 'form-control'}) %}
        {% endif %}
        <div class="form-group clearfix">
            {{ form_label(form) }}
            {{ form_widget(form, { 'attr': attr }) }}
            {{ form_errors(form) }}
        </div>
    {% endspaceless %}
{% endblock form_row %}

{% block form_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            {% for error in errors %}
                <div class="label label-danger">{{ error.message }}</div>
            {% endfor %}
        {% endif %}
    {% endspaceless %}
{% endblock form_errors %}

{% block controls %}
    {#{{ dump(form.vars.accept) }}#}
    <div class="juice_upload_controls clearfix">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <div class="juice_upload_button_container">
            <span class="btn btn-primary fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>{{ form.vars.button_label }}</span>

                <!-- The file input field used as target for the file upload widget -->
                <input class="file_upload" type="file" name="file" accept="{{ form.vars.accept }}"  {% if form.vars.multi | default(false) %}multiple{% endif %}>
            </span>
        </div>

        <div class="juice_upload_progress_container">
            <div class="percent"></div>
            <span class="glyphicon glyphicon-refresh spin"></span>
        </div>
    </div>
{% endblock %}

{% block juice_gallery_collection_widget %}
    {% spaceless %}
        <div class="form-control {{ form.vars.upload_class }}">
            <div class="juice_upload_container clearfix" data-prototype="{{ form_widget(form.vars.prototype) | e }}" {% for key, value in form.vars.attr %}{{ key }}="{{ value }}" {% endfor %}>

                {{ block('controls') }}

                <div class="juice_upload_collection_container clearfix">
                    {% for fields in form %}
                        <div class="juice_upload_item">
                            <div class="featured_layer"></div>
                            <div class="edit_layer">
                                <div class="buttons">
                                    <div class="button remove"><span class="glyphicon glyphicon-remove"></span></div>
                                </div>
                            </div>
                            <div class="preview">
                                {% if fields.vars.value.id %}
                                    <img src="/media/{{ fields.vars.value.photo }}" />
                                {%  else %}
                                    <img src="/uploads/{{ fields.vars.value.photo }}" />
                                {%  endif %}

                            </div>
                            <div class="hidden_form upload_form">{{ form_widget(fields) }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endspaceless %}
{% endblock juice_gallery_collection_widget %}

{% block juice_image_type_widget %}
    <div class="juice_upload_container clearfix" {% for key, value in form.vars.attr %}{{ key }}="{{ value }}" {% endfor %} data-input-name="{{ form.vars.full_name }}">
    
        {{ block('controls') }}

        <div class="juice_upload_item single_item">
            <div class="featured_layer"></div>
            <div class="edit_layer">
                <div class="buttons">
                    <div class="button remove"><span class="glyphicon glyphicon-remove"></span></div>
                </div>
            </div>
            <div class="preview juice_upload_form_container">
                {% if form.vars.value %}
                    {% set finalPath = final_upload_dir ~ "/" ~ form.vars.value %}
                    {% set tmpPath = tmp_upload_dir ~ "/" ~ form.vars.value %}

                    {% if form.parent.vars.value.id and finalPath | checkFile %}
                        <img src="/{{ finalPath }}" />
                    {%  elseif tmpPath | checkFile%}
                        <img src="/{{ tmpPath }}" />
                    {%  else %}
                        Image ERROR!!!
                    {%  endif %}
                    <div class="hidden_form">{{ form_widget(form) }}</div>
                {%  endif %}
            </div>
        </div>
    </div>
{% endblock juice_image_type_widget %}

{% block juice_file_type_widget %}
    <div class="juice_upload_container clearfix" {% for key, value in form.vars.attr %}{{ key }}="{{ value }}" {% endfor %} data-input-name="{{ form.vars.full_name }}">

    {{ block('controls') }}

        <div class="juice_upload_item single_item ">
            <div class="juice_upload_form_container">
            {% if form.vars.value %}
                <div class="alert alert-success juice_upload_single_file" role="alert">{{ form.vars.value }}<div class="button remove"><span class="glyphicon glyphicon-remove"></span></div></div>
                <div class="hidden_form">{{ form_widget(form) }}</div>
            {%  endif %}
            </div>
        </div>
    </div>
{% endblock juice_file_type_widget %}

{% block juice_gallery_item_type_widget %}
    {#<div class="hidden_form upload_form">{{ form_widget(form) }}</div>#}
{% endblock juice_gallery_item_type_widget %}